name: ${DOCKER_COMPOSE_NAME:-aavnhtmxdemo}

services:
  website:
    build:
      context: website/
      dockerfile: Dockerfile
      target: base
      args:
        - XDEBUG_ENABLE=${XDEBUG_ENABLE:-0}
    volumes:
      - ../src-website:/var/www/html
    ports:
      - "${WEBSITE_PORT:-8023}:443"
    depends_on:
      - database
  
  database:
    image: mysql:9.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-aavnhtmxdemo}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-aavnhtmxdemo}
      MYSQL_USER: ${MYSQL_USER:-aavnhtmxdemo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-aavnhtmxdemo}
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-gsv}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-gsv}
    ports:
      - "${PHPMYADMIN_PORT:-53236}:80"
    depends_on:
      - database

volumes:
  database_data: